-- ============================================================
-- HOTEL QUINTA DALAM - Esquema PostgreSQL 15+
-- Objetivo: Reservas de alojamiento con ACID + anti-solapamiento
-- ============================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS hotel;
SET search_path TO hotel, public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS citext;

-- =========================
-- Tipos Enumerados
-- =========================
CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'LOCKED');
CREATE TYPE role_code AS ENUM ('OBSERVER', 'GUEST', 'ADMIN');
CREATE TYPE room_status AS ENUM ('ACTIVE', 'INACTIVE', 'MAINTENANCE');
CREATE TYPE reservation_status AS ENUM (
  'PENDING_PAYMENT',
  'CONFIRMED',
  'CHECKED_IN',
  'CHECKED_OUT',
  'CANCELLED',
  'NO_SHOW'
);
CREATE TYPE payment_status AS ENUM (
  'CREATED',
  'REQUIRES_ACTION',
  'SUCCEEDED',
  'FAILED',
  'CANCELED',
  'REFUNDED'
);
CREATE TYPE payment_provider AS ENUM ('STRIPE');

-- =========================
-- Seguridad / Usuarios
-- =========================
CREATE TABLE roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code role_code NOT NULL UNIQUE,
  name VARCHAR(40) NOT NULL UNIQUE,
  description TEXT NOT NULL
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email CITEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  phone VARCHAR(30),
  status user_status NOT NULL DEFAULT 'ACTIVE',
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_user_phone_format CHECK (
    phone IS NULL OR phone ~ '^[0-9+()\\-\\s]{8,30}$'
  )
);

CREATE TABLE user_roles (
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id SMALLINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, role_id)
);

-- =========================
-- Inventario de Habitaciones
-- =========================
CREATE TABLE rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(50) NOT NULL UNIQUE,              -- Ej. suite-patzcuaro
  name VARCHAR(120) NOT NULL UNIQUE,             -- Ej. Suite Pátzcuaro
  subtitle VARCHAR(180),
  category VARCHAR(60) NOT NULL,                 -- Ej. Suite Superior
  description TEXT,
  capacity SMALLINT NOT NULL,
  size_m2 NUMERIC(6,2),
  bed_type VARCHAR(80),
  status room_status NOT NULL DEFAULT 'ACTIVE',
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_room_capacity_positive CHECK (capacity > 0),
  CONSTRAINT chk_room_size_positive CHECK (size_m2 IS NULL OR size_m2 > 0)
);

CREATE TABLE room_amenities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(40) NOT NULL UNIQUE,              -- wifi, desayuno, tina
  name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE room_amenity_map (
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  amenity_id UUID NOT NULL REFERENCES room_amenities(id) ON DELETE RESTRICT,
  PRIMARY KEY (room_id, amenity_id)
);

-- Tarifas dinámicas (vigencia por rango, no solapable por habitación)
CREATE TABLE room_rates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  valid_during DATERANGE NOT NULL,               -- [inicio, fin)
  nightly_rate_amount NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'MXN',
  note TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_rate_amount_positive CHECK (nightly_rate_amount > 0),
  CONSTRAINT chk_rate_currency_iso CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_rate_range_valid CHECK (lower(valid_during) < upper(valid_during)),
  CONSTRAINT ex_room_rate_no_overlap EXCLUDE USING gist (
    room_id WITH =,
    valid_during WITH &&
  )
);

-- =========================
-- Reservas + Cobros
-- =========================
CREATE SEQUENCE reservation_folio_seq START 1000;

CREATE TABLE reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reservation_code VARCHAR(30) NOT NULL UNIQUE,  -- Ej. RES-20260501-01000
  guest_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,

  status reservation_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  stay_range DATERANGE GENERATED ALWAYS AS (daterange(check_in, check_out, '[)')) STORED,
  nights INTEGER GENERATED ALWAYS AS (check_out - check_in) STORED,
  guests_count SMALLINT NOT NULL,

  -- Snapshot de datos del huésped al momento de compra
  guest_full_name VARCHAR(180) NOT NULL,
  guest_email CITEXT NOT NULL,
  guest_phone VARCHAR(30),

  -- Snapshot de precio al comprar (inmutable para historial financiero)
  nightly_rate_amount NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'MXN',
  subtotal_amount NUMERIC(12,2) NOT NULL,
  taxes_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL,

  special_requests TEXT,
  cancellation_reason TEXT,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_reservation_dates CHECK (check_out > check_in),
  CONSTRAINT chk_reservation_guests_positive CHECK (guests_count > 0),
  CONSTRAINT chk_reservation_phone_format CHECK (
    guest_phone IS NULL OR guest_phone ~ '^[0-9+()\\-\\s]{8,30}$'
  ),
  CONSTRAINT chk_reservation_currency_iso CHECK (currency ~ '^[A-Z]{3}$'),
  CONSTRAINT chk_reservation_nightly_positive CHECK (nightly_rate_amount > 0),
  CONSTRAINT chk_reservation_subtotal_positive CHECK (subtotal_amount > 0),
  CONSTRAINT chk_reservation_taxes_non_negative CHECK (taxes_amount >= 0),
  CONSTRAINT chk_reservation_total_positive CHECK (total_amount > 0),

  -- Prevención de solapamiento por habitación (solo estados bloqueantes)
  CONSTRAINT ex_reservation_no_overlap
    EXCLUDE USING gist (
      room_id WITH =,
      stay_range WITH &&
    )
    WHERE (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CHECKED_IN'))
);

CREATE TABLE reservation_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  old_status reservation_status,
  new_status reservation_status NOT NULL,
  changed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  reason TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reservation_id UUID NOT NULL REFERENCES reservations(id) ON DELETE RESTRICT,
  provider payment_provider NOT NULL DEFAULT 'STRIPE',
  status payment_status NOT NULL DEFAULT 'CREATED',
  amount NUMERIC(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'MXN',
  stripe_session_id VARCHAR(255) NOT NULL UNIQUE,
  stripe_payment_intent_id VARCHAR(255),
  paid_at TIMESTAMPTZ,
  raw_gateway_payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_payment_amount_positive CHECK (amount > 0),
  CONSTRAINT chk_payment_currency_iso CHECK (currency ~ '^[A-Z]{3}$')
);

-- =========================
-- Índices de desempeño
-- =========================
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_rooms_status ON rooms(status);
CREATE INDEX idx_rates_room_lower ON room_rates(room_id, lower(valid_during));
CREATE INDEX idx_reservations_guest ON reservations(guest_user_id, check_in DESC);
CREATE INDEX idx_reservations_room_dates ON reservations(room_id, check_in, check_out);
CREATE INDEX idx_reservations_status_dates ON reservations(status, check_in, check_out);
CREATE INDEX idx_payments_reservation ON payments(reservation_id, created_at DESC);
CREATE INDEX idx_payments_status ON payments(status);

-- =========================
-- Triggers y funciones
-- =========================
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_assign_reservation_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.reservation_code IS NULL OR NEW.reservation_code = '' THEN
    NEW.reservation_code :=
      'RES-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' ||
      LPAD(nextval('reservation_folio_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_fill_reservation_pricing()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_rate NUMERIC(12,2);
  v_currency CHAR(3);
  v_nights INTEGER;
BEGIN
  v_nights := NEW.check_out - NEW.check_in;
  IF v_nights <= 0 THEN
    RAISE EXCEPTION 'Rango de fechas invalido: check_out debe ser mayor a check_in';
  END IF;

  -- Si el backend no envía tarifa, se toma la tarifa vigente al check-in.
  IF NEW.nightly_rate_amount IS NULL OR NEW.nightly_rate_amount <= 0 OR NEW.currency IS NULL THEN
    SELECT rr.nightly_rate_amount, rr.currency
      INTO v_rate, v_currency
    FROM room_rates rr
    WHERE rr.room_id = NEW.room_id
      AND rr.valid_during @> NEW.check_in
    ORDER BY lower(rr.valid_during) DESC, rr.created_at DESC
    LIMIT 1;

    IF v_rate IS NULL THEN
      RAISE EXCEPTION 'No existe tarifa vigente para room_id % y fecha %', NEW.room_id, NEW.check_in;
    END IF;

    IF NEW.nightly_rate_amount IS NULL OR NEW.nightly_rate_amount <= 0 THEN
      NEW.nightly_rate_amount := v_rate;
    END IF;
    IF NEW.currency IS NULL THEN
      NEW.currency := v_currency;
    END IF;
  END IF;

  NEW.subtotal_amount := NEW.nightly_rate_amount * v_nights;
  NEW.taxes_amount := COALESCE(NEW.taxes_amount, 0);
  NEW.total_amount := COALESCE(NEW.total_amount, NEW.subtotal_amount + NEW.taxes_amount);

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_audit_reservation_status()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO reservation_status_history(reservation_id, old_status, new_status, reason)
    VALUES (NEW.id, NULL, NEW.status, 'Creación');
    RETURN NEW;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO reservation_status_history(reservation_id, old_status, new_status, reason)
    VALUES (NEW.id, OLD.status, NEW.status, NEW.cancellation_reason);

    IF NEW.status = 'CANCELLED' AND NEW.cancelled_at IS NULL THEN
      NEW.cancelled_at := NOW();
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_prevent_reservation_delete()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'DELETE físico no permitido en reservations. Use status = CANCELLED (soft delete).';
END;
$$;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_rooms_updated_at
BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_reservations_updated_at
BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_reservation_code
BEFORE INSERT ON reservations
FOR EACH ROW EXECUTE FUNCTION fn_assign_reservation_code();

CREATE TRIGGER trg_reservation_pricing
BEFORE INSERT OR UPDATE OF room_id, check_in, check_out, nightly_rate_amount, taxes_amount, currency, total_amount
ON reservations
FOR EACH ROW EXECUTE FUNCTION fn_fill_reservation_pricing();

CREATE TRIGGER trg_reservation_status_audit
BEFORE INSERT OR UPDATE OF status, cancellation_reason
ON reservations
FOR EACH ROW EXECUTE FUNCTION fn_audit_reservation_status();

CREATE TRIGGER trg_prevent_reservation_delete
BEFORE DELETE ON reservations
FOR EACH ROW EXECUTE FUNCTION fn_prevent_reservation_delete();

-- =========================
-- Datos base de roles
-- =========================
INSERT INTO roles(code, name, description) VALUES
  ('OBSERVER', 'Observador', 'Solo lectura de panel y reportes'),
  ('GUEST', 'Huésped', 'Usuario cliente que gestiona su perfil y reservas'),
  ('ADMIN', 'Administrador', 'Control total del sistema')
ON CONFLICT (code) DO NOTHING;

COMMIT;
